---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: kube-ops-view
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://codeberg.org/hjacobs/kube-ops-view
